spring:
  datasource:
    username: root
    password: 321123
    url: jdbc:mysql://localhost:3306/networkdisk
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: static/**
  mail:
    host: smtp.163.com
    username: zl1813890249@163.com
    password: RGQLGIKMKWGFGURY
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl