spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/networkdisk
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: static/**
  mail:
    host: smtp.163.com
    username: zl1813890249@163.com
    password: RGQLGIKMKWGFGURY
mybatis:
  #配置mapper xml文件的路径
  mapper-locations: classpath:sql/mapper/*.xml
  #开启SQL日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  #服务器地址目录
  windows-upload-path: /root/networkdisk/download/
  #HDFS地址目录
  hdfs-upload-path: /HDFS/
  #限制文件类型
  file-type-array: .png,.jpg,.jpeg,.txt,.zip,.rar,.pdf,.xml,.xls,.doc,.docx
  #最大文件大小
  max-file-size: 8192
  #用户文件存放地址目录
  user-file-path: /root/networkdisk/User/
logging:
    file:
      name: /root/networkdisk/log/log4j.log
      max-size: 512KB